In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("25k IMDb movie Dataset.csv")

In [3]:
data.head()

,movie title,Run Time,Rating,User Rating,Generes,Overview,Plot Kyeword,Director,Top 5 Casts,Writer,year,path
0,Top Gun: Maverick,"$170,000,000 (estimated)",8.6,187K,"['Action', 'Drama']",After more than thirty years of service as one...,"['fighter jet', 'sequel', 'u.s. navy', 'fighte...",Joseph Kosinski,"['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...",Jim Cash,-2022,/title/tt1745960/
1,Jurassic World Dominion,2 hours 27 minutes,6,56K,"['Action', 'Adventure', 'Sci-Fi']",Four years after the destruction of Isla Nubla...,"['dinosaur', 'jurassic park', 'tyrannosaurus r...",Colin Trevorrow,"['Colin Trevorrow', 'Derek Connolly', 'Chris P...",Emily Carmichael,-2022,/title/tt8041270/
2,Top Gun,"$15,000,000 (estimated)",6.9,380K,"['Action', 'Drama']",As students at the United States Navy's elite ...,"['pilot', 'male camaraderie', 'u.s. navy', 'gr...",Tony Scott,"['Jack Epps Jr.', 'Ehud Yonay', 'Tom Cruise', ...",Jim Cash,-1986,/title/tt0092099/
3,Lightyear,"$71,101,257",5.2,32K,"['Animation', 'Action', 'Adventure']",While spending years attempting to return home...,"['galaxy', 'spaceship', 'robot', 'rocket', 'sp...",Angus MacLane,"['Jason Headley', 'Matthew Aldrich', 'Chris Ev...",Angus MacLane,-2022,/title/tt10298810/
4,Spiderhead,not-released,5.4,23K,"['Action', 'Crime', 'Drama']","In the near future, convicts are offered the c...","['discover', 'medical', 'test', 'reality', 'fi...",Joseph Kosinski,"['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...",George Saunders,-2022,/title/tt9783600/

In [4]:
data.tail()

,movie title,Run Time,Rating,User Rating,Generes,Overview,Plot Kyeword,Director,Top 5 Casts,Writer,year,path
24397,Delicatessen,"FRFÂ 24,000,000 (estimated)",7.6,85K,"['Comedy', 'Crime']",Post-apocalyptic surrealist black comedy about...,"['surrealist', 'black comedy', 'human meat', '...",Marc Caro,"['Jean-Pierre Jeunet', 'Marc Caro', 'Gilles Ad...",Jean-Pierre Jeunet,-1991,/title/tt0101700/
24398,Bitch Ass,not-released,5.5,52,"['Crime', 'Horror']",A gang initiation goes wrong when a group of f...,[],Bill Posley,"['Bill Posley', 'Teon Kelley', 'Tunde Laleye',...",Jonathan Colomb,-2022,/title/tt13991504/
24399,Bullwhip,not-released,5.1,398,"['Crime', 'Romance', 'Western']","In order to avoid the hangman's noose, a cowbo...","['taming of the shrew', 'fur trader', 'busines...",Harmon Jones,"['Guy Madison', 'Rhonda Fleming', 'James Griff...",Adele Buffington,-1958,/title/tt0051438/
24400,The Freshman,1 hour 42 minutes,6.4,20K,"['Comedy', 'Crime']",An N.Y.C. film school student accepts a job wi...,"['endangered species', 'fish out of water', 'g...",Andrew Bergman,"['Marlon Brando', 'Matthew Broderick', 'Bruno ...",Andrew Bergman,-1990,/title/tt0099615/
24401,Guys and Dolls,"$5,500,000 (estimated)",7.1,18K,"['Comedy', 'Crime', 'Musical']","In New York, a gambler is challenged to take a...","['mission', 'gambler', 'new york city', 'based...",Joseph L. Mankiewicz,"['Abe Burrows', 'Damon Runyon', 'Marlon Brando...",Jo Swerling,-1955,/title/tt0048140/

In [5]:
data.columns

Index(['movie title', 'Run Time', 'Rating', 'User Rating', 'Generes',
       'Overview', 'Plot Kyeword', 'Director', 'Top 5 Casts', 'Writer', 'year',
       'path'],
      dtype='object')

In [6]:
data.count()

movie title     24402
Run Time        24402
Rating          24402
User Rating     24402
Generes         24402
Overview        24158
Plot Kyeword    24402
Director        24402
Top 5 Casts     24402
Writer          24402
year            23624
path            24402
dtype: int64

In [7]:
data.nunique()

movie title     23922
Run Time         1556
Rating             91
User Rating      1684
Generes           746
Overview        23957
Plot Kyeword    21546
Director        11604
Top 5 Casts     24211
Writer          15562
year              250
path            23922
dtype: int64

In [8]:
del(data['path'])

In [9]:
del(data['Overview'])

In [10]:
del(data['Plot Kyeword'])

In [11]:
data

,movie title,Run Time,Rating,User Rating,Generes,Director,Top 5 Casts,Writer,year
0,Top Gun: Maverick,"$170,000,000 (estimated)",8.6,187K,"['Action', 'Drama']",Joseph Kosinski,"['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...",Jim Cash,-2022
1,Jurassic World Dominion,2 hours 27 minutes,6,56K,"['Action', 'Adventure', 'Sci-Fi']",Colin Trevorrow,"['Colin Trevorrow', 'Derek Connolly', 'Chris P...",Emily Carmichael,-2022
2,Top Gun,"$15,000,000 (estimated)",6.9,380K,"['Action', 'Drama']",Tony Scott,"['Jack Epps Jr.', 'Ehud Yonay', 'Tom Cruise', ...",Jim Cash,-1986
3,Lightyear,"$71,101,257",5.2,32K,"['Animation', 'Action', 'Adventure']",Angus MacLane,"['Jason Headley', 'Matthew Aldrich', 'Chris Ev...",Angus MacLane,-2022
4,Spiderhead,not-released,5.4,23K,"['Action', 'Crime', 'Drama']",Joseph Kosinski,"['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...",George Saunders,-2022
...,...,...,...,...,...,...,...,...,...
24397,Delicatessen,"FRFÂ 24,000,000 (estimated)",7.6,85K,"['Comedy', 'Crime']",Marc Caro,"['Jean-Pierre Jeunet', 'Marc Caro', 'Gilles Ad...",Jean-Pierre Jeunet,-1991
24398,Bitch Ass,not-released,5.5,52,"['Crime', 'Horror']",Bill Posley,"['Bill Posley', 'Teon Kelley', 'Tunde Laleye',...",Jonathan Colomb,-2022
24399,Bullwhip,not-released,5.1,398,"['Crime', 'Romance', 'Western']",Harmon Jones,"['Guy Madison', 'Rhonda Fleming', 'James Griff...",Adele Buffington,-1958
24400,The Freshman,1 hour 42 minutes,6.4,20K,"['Comedy', 'Crime']",Andrew Bergman,"['Marlon Brando', 'Matthew Broderick', 'Bruno ...",Andrew Bergman,-1990
24401,Guys and Dolls,"$5,500,000 (estimated)",7.1,18K,"['Comedy', 'Crime', 'Musical']",Joseph L. Mankiewicz,"['Abe Burrows', 'Damon Runyon', 'Marlon Brando...",Jo Swerling,-1955

In [12]:
data.dtypes

movie title    object
Run Time       object
Rating         object
User Rating    object
Generes        object
Director       object
Top 5 Casts    object
Writer         object
year           object
dtype: object

In [13]:
data[data['year'].isnull()]

,movie title,Run Time,Rating,User Rating,Generes,Director,Top 5 Casts,Writer,year
495,Napoleon,not-released,no-rating,0,"['Action', 'Biography', 'Drama']",Ridley Scott,"['Vanessa Kirby', 'Joaquin Phoenix', 'Ludivine...",David Scarpa,NaN
496,Napoleon,5 hours 30 minutes,8.2,7.8K,"['Biography', 'Drama', 'History']",Abel Gance,"['Albert DieudonnÃ©', 'Vladimir Roudenko', 'Edm...",Abel Gance,NaN
562,I Saw the Devil,2 hours 24 minutes,7.8,127K,"['Action', 'Crime', 'Drama']",Jee-woon Kim,"['Jee-woon Kim', 'Lee Byung-hun', 'Choi Min-si...",Park Hoon-jung,NaN
563,I Saw the Devil,not-released,no-rating,0,"['Action', 'Horror', 'Thriller']",Simon Barrett,"['Simon Barrett', 'Park Hoon-jung', 'United St...",Park Hoon-jung,NaN
717,Sherlock Holmes 3,not-released,no-rating,0,"['Action', 'Adventure', 'Mystery']",Dexter Fletcher,"['Arthur Conan Doyle', 'Robert Downey Jr.', 'J...",Chris Brancato,NaN
...,...,...,...,...,...,...,...,...,...
24253,L.A. Rush,not-released,no-rating,0,"['Crime', 'Drama']",Jiahuang Peng,"['Peng Chen', 'Elijah Wood', 'Whitney Anderson...",Peng Chen,NaN
24270,Crimelands,not-released,no-rating,0,['Crime'],Jonny Wilson,"['Jonny Wilson', 'Ariel Winter', 'Clive Stande...",Colin Muir,NaN
24303,Catch and Kill,not-released,no-rating,0,"['Crime', 'Drama', 'Horror']",Brian De Palma,"['Brian De Palma', 'Brian De Palma', 'France',...",Brian De Palma,NaN
24304,Rent-a-Man,not-released,no-rating,0,"['Crime', 'Drama', 'Mystery']",Rafal Zlak,"['Rafal Zlak', 'Jomri D.', 'Jakub Baranski', '...",Rafal Zlak,NaN
24321,8 1/2,not-released,no-rating,0,['Crime'],Susanna Lo,"['Susanna Lo', 'Susanna Lo', 'United States', ...",Susanna Lo,NaN

In [14]:
data.dropna(subset= ['year'], inplace= True)

In [15]:
data

,movie title,Run Time,Rating,User Rating,Generes,Director,Top 5 Casts,Writer,year
0,Top Gun: Maverick,"$170,000,000 (estimated)",8.6,187K,"['Action', 'Drama']",Joseph Kosinski,"['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...",Jim Cash,-2022
1,Jurassic World Dominion,2 hours 27 minutes,6,56K,"['Action', 'Adventure', 'Sci-Fi']",Colin Trevorrow,"['Colin Trevorrow', 'Derek Connolly', 'Chris P...",Emily Carmichael,-2022
2,Top Gun,"$15,000,000 (estimated)",6.9,380K,"['Action', 'Drama']",Tony Scott,"['Jack Epps Jr.', 'Ehud Yonay', 'Tom Cruise', ...",Jim Cash,-1986
3,Lightyear,"$71,101,257",5.2,32K,"['Animation', 'Action', 'Adventure']",Angus MacLane,"['Jason Headley', 'Matthew Aldrich', 'Chris Ev...",Angus MacLane,-2022
4,Spiderhead,not-released,5.4,23K,"['Action', 'Crime', 'Drama']",Joseph Kosinski,"['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...",George Saunders,-2022
...,...,...,...,...,...,...,...,...,...
24397,Delicatessen,"FRFÂ 24,000,000 (estimated)",7.6,85K,"['Comedy', 'Crime']",Marc Caro,"['Jean-Pierre Jeunet', 'Marc Caro', 'Gilles Ad...",Jean-Pierre Jeunet,-1991
24398,Bitch Ass,not-released,5.5,52,"['Crime', 'Horror']",Bill Posley,"['Bill Posley', 'Teon Kelley', 'Tunde Laleye',...",Jonathan Colomb,-2022
24399,Bullwhip,not-released,5.1,398,"['Crime', 'Romance', 'Western']",Harmon Jones,"['Guy Madison', 'Rhonda Fleming', 'James Griff...",Adele Buffington,-1958
24400,The Freshman,1 hour 42 minutes,6.4,20K,"['Comedy', 'Crime']",Andrew Bergman,"['Marlon Brando', 'Matthew Broderick', 'Bruno ...",Andrew Bergman,-1990
24401,Guys and Dolls,"$5,500,000 (estimated)",7.1,18K,"['Comedy', 'Crime', 'Musical']",Joseph L. Mankiewicz,"['Abe Burrows', 'Damon Runyon', 'Marlon Brando...",Jo Swerling,-1955

In [16]:
data.nunique()

movie title    23153
Run Time        1553
Rating            91
User Rating     1684
Generes          737
Director       11294
Top 5 Casts    23545
Writer         15181
year             250
dtype: int64

In [17]:
data[data['movie title'].duplicated()]

,movie title,Run Time,Rating,User Rating,Generes,Director,Top 5 Casts,Writer,year
7,Interceptor,1 hour 30 minutes,3.6,819,"['Action', 'Sci-Fi', 'Thriller']",Konstantin Maksimov,"['Konstantin Maksimov', 'Larisa Stepanova', 'I...",Vasily Golovachov,-2022
18,Bullet Train,not-released,6.8,1.3K,"['Action', 'Crime', 'Drama']",Jun'ya SatÃ´,"[""Jun'ya SatÃ´"", 'Sunao Sakagami', 'Ken Takakur...",RyÃ»nosuke Ono,-2022
29,Prey,not-released,5.2,961,"['Adventure', 'Drama', 'Horror']",Antoine Blossier,"['Erich Vogel', 'GrÃ©goire Colin', 'FranÃ§ois Le...",Antoine Blossier,(I) (2022)
30,Prey,1 hour 48 minutes,5.3,2.5K,"['Comedy', 'Horror', 'Thriller']",Dick Maas,"['Julian Looman', 'Abbey Hoes', 'Mark Frost', ...",Dick Maas,(I) (2022)
32,Ambulance,1 hour 20 minutes,5.3,1.4K,"['Action', 'Drama', 'Thriller']",Laurits Munch-Petersen,"['Lars Andreas Pedersen', 'Paw Henriksen', 'Th...",Laurits Munch-Petersen,-2022
...,...,...,...,...,...,...,...,...,...
22309,The Isle,1 hour 36 minutes,5.3,13K,"['Fantasy', 'Mystery', 'Thriller']",Matthew Butler-Hart,"['Tori Butler-Hart', 'Conleth Hill', 'Alex Has...",Matthew Butler-Hart,-2018
22482,The Concrete Jungle,1 hour 26 minutes,6.8,1.6K,"['Crime', 'Drama', 'Thriller']",Joseph Losey,"['Jimmy Sangster', 'Stanley Baker', 'Sam Wanam...",Alun Owen,-1982
22635,The Bunker,not-released,5.4,6K,"['Drama', 'Horror', 'Mystery']",Rob Green,"['Jason Flemyng', 'Andrew Tiernan', 'Christoph...",Clive Dawson,-2001
22720,Almost Human,not-released,7.2,2.5K,"['Crime', 'Drama', 'Thriller']",Umberto Lenzi,"['Tomas Milian', 'Henry Silva', 'Laura Belli',...",Ernesto Gastaldi,-2013
22740,Escape,not-released,3.5,50,['Thriller'],Sarshick Roshan,"['Sreevidya Mullachery', 'Arun Kumar', 'Sarshi...",Gayathri Suresh,(II) (2022)

In [18]:
data.drop_duplicates(subset=['movie title'], inplace= True)

In [19]:
data

,movie title,Run Time,Rating,User Rating,Generes,Director,Top 5 Casts,Writer,year
0,Top Gun: Maverick,"$170,000,000 (estimated)",8.6,187K,"['Action', 'Drama']",Joseph Kosinski,"['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...",Jim Cash,-2022
1,Jurassic World Dominion,2 hours 27 minutes,6,56K,"['Action', 'Adventure', 'Sci-Fi']",Colin Trevorrow,"['Colin Trevorrow', 'Derek Connolly', 'Chris P...",Emily Carmichael,-2022
2,Top Gun,"$15,000,000 (estimated)",6.9,380K,"['Action', 'Drama']",Tony Scott,"['Jack Epps Jr.', 'Ehud Yonay', 'Tom Cruise', ...",Jim Cash,-1986
3,Lightyear,"$71,101,257",5.2,32K,"['Animation', 'Action', 'Adventure']",Angus MacLane,"['Jason Headley', 'Matthew Aldrich', 'Chris Ev...",Angus MacLane,-2022
4,Spiderhead,not-released,5.4,23K,"['Action', 'Crime', 'Drama']",Joseph Kosinski,"['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...",George Saunders,-2022
...,...,...,...,...,...,...,...,...,...
24397,Delicatessen,"FRFÂ 24,000,000 (estimated)",7.6,85K,"['Comedy', 'Crime']",Marc Caro,"['Jean-Pierre Jeunet', 'Marc Caro', 'Gilles Ad...",Jean-Pierre Jeunet,-1991
24398,Bitch Ass,not-released,5.5,52,"['Crime', 'Horror']",Bill Posley,"['Bill Posley', 'Teon Kelley', 'Tunde Laleye',...",Jonathan Colomb,-2022
24399,Bullwhip,not-released,5.1,398,"['Crime', 'Romance', 'Western']",Harmon Jones,"['Guy Madison', 'Rhonda Fleming', 'James Griff...",Adele Buffington,-1958
24400,The Freshman,1 hour 42 minutes,6.4,20K,"['Comedy', 'Crime']",Andrew Bergman,"['Marlon Brando', 'Matthew Broderick', 'Bruno ...",Andrew Bergman,-1990
24401,Guys and Dolls,"$5,500,000 (estimated)",7.1,18K,"['Comedy', 'Crime', 'Musical']",Joseph L. Mankiewicz,"['Abe Burrows', 'Damon Runyon', 'Marlon Brando...",Jo Swerling,-1955

In [20]:
data['Run Time'].value_counts()

not-released                  7558
1 hour 30 minutes              491
1 hour 35 minutes              367
1 hour 38 minutes              345
1 hour 31 minutes              334
                              ...
$795,000 (estimated)             1
$6,900,000 (estimated)           1
$28,596,818                      1
$22,873,653                      1
FRFÂ 24,000,000 (estimated)       1
Name: Run Time, Length: 1524, dtype: int64

In [21]:
del(data['Run Time'])

In [22]:
data

,movie title,Rating,User Rating,Generes,Director,Top 5 Casts,Writer,year
0,Top Gun: Maverick,8.6,187K,"['Action', 'Drama']",Joseph Kosinski,"['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...",Jim Cash,-2022
1,Jurassic World Dominion,6,56K,"['Action', 'Adventure', 'Sci-Fi']",Colin Trevorrow,"['Colin Trevorrow', 'Derek Connolly', 'Chris P...",Emily Carmichael,-2022
2,Top Gun,6.9,380K,"['Action', 'Drama']",Tony Scott,"['Jack Epps Jr.', 'Ehud Yonay', 'Tom Cruise', ...",Jim Cash,-1986
3,Lightyear,5.2,32K,"['Animation', 'Action', 'Adventure']",Angus MacLane,"['Jason Headley', 'Matthew Aldrich', 'Chris Ev...",Angus MacLane,-2022
4,Spiderhead,5.4,23K,"['Action', 'Crime', 'Drama']",Joseph Kosinski,"['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...",George Saunders,-2022
...,...,...,...,...,...,...,...,...
24397,Delicatessen,7.6,85K,"['Comedy', 'Crime']",Marc Caro,"['Jean-Pierre Jeunet', 'Marc Caro', 'Gilles Ad...",Jean-Pierre Jeunet,-1991
24398,Bitch Ass,5.5,52,"['Crime', 'Horror']",Bill Posley,"['Bill Posley', 'Teon Kelley', 'Tunde Laleye',...",Jonathan Colomb,-2022
24399,Bullwhip,5.1,398,"['Crime', 'Romance', 'Western']",Harmon Jones,"['Guy Madison', 'Rhonda Fleming', 'James Griff...",Adele Buffington,-1958
24400,The Freshman,6.4,20K,"['Comedy', 'Crime']",Andrew Bergman,"['Marlon Brando', 'Matthew Broderick', 'Bruno ...",Andrew Bergman,-1990
24401,Guys and Dolls,7.1,18K,"['Comedy', 'Crime', 'Musical']",Joseph L. Mankiewicz,"['Abe Burrows', 'Damon Runyon', 'Marlon Brando...",Jo Swerling,-1955

In [23]:
data['Rating'].value_counts()

no-rating    948
6.4          833
6.2          832
6.3          798
6.1          796
            ...
9.9            2
9.8            2
9.4            2
1              2
9.5            2
Name: Rating, Length: 91, dtype: int64

In [24]:
data['User Rating'].value_counts()

0       948
11K     320
1.2K    316
1.1K    312
1.3K    286
       ...
674K      1
614K      1
452K      1
530K      1
347K      1
Name: User Rating, Length: 1681, dtype: int64

In [25]:
data[data['User Rating'] == '0']

,movie title,Rating,User Rating,Generes,Director,Top 5 Casts,Writer,year
8,Black Adam,no-rating,0,"['Action', 'Fantasy', 'Sci-Fi']",Jaume Collet-Serra,"['Rory Haines', 'Sohrab Noshirvani', 'Sarah Sh...",Adam Sztykiel,-2022
17,Bullet Train,no-rating,0,"['Action', 'Thriller']",David Leitch,"['Zak Olkewicz', 'Karen Fukuhara', 'Brad Pitt'...",KÃ´tarÃ´ Isaka,-2022
28,Prey,no-rating,0,"['Action', 'Drama', 'Horror']",Dan Trachtenberg,"['Amber Midthunder', 'Dane DiLiegro', 'Harlan ...",Patrick Aison,(I) (2022)
38,The Gray Man,no-rating,0,"['Action', 'Thriller']",Anthony Russo,"['Mark Greaney', 'Joe Russo', 'Christopher Mar...",Joe Russo,-2022
59,Avatar: The Way of Water,no-rating,0,"['Action', 'Adventure', 'Sci-Fi']",James Cameron,"['Josh Friedman', 'Michelle Yeoh', 'Zoe Saldan...",James Cameron,-2022
...,...,...,...,...,...,...,...,...
24242,Scheme Queens,no-rating,0,['Crime'],Cas Sigers-Beedles,"[""Brii Renee'"", 'Jason Louder', 'Sean Baker', ...",Cas Sigers-Beedles,-2022
24311,Penthouse,no-rating,0,"['Crime', 'Mystery', 'Thriller']",Abbas Alibhai Burmawalla,"['Girish Dhamija', 'Mouni Roy', 'Tisca Chopra'...",Mastan Alibhai Burmawalla,(I) (2022)
24355,Now I See,no-rating,0,"['Crime', 'Drama']",Carissa Stutzman,"['Annalise Basso', 'Steven Ogg', 'Deborah Tuck...",Carissa Stutzman,-2023
24377,Flycatcher,no-rating,0,"['Crime', 'Drama', 'Thriller']",Phil Volken,"['Phil Volken', 'Phil Volken', '2023 (United S...",Phil Volken,-2023
24379,Breakwater,no-rating,0,"['Crime', 'Drama', 'Thriller']",James Rowe,"['Mena Suvari', 'Dermot Mulroney', 'Celia Rose...",James Rowe,(I) (2022)

In [26]:
data[(data['User Rating'] == '0') & (data['Rating'] =='no-rating')]

,movie title,Rating,User Rating,Generes,Director,Top 5 Casts,Writer,year
8,Black Adam,no-rating,0,"['Action', 'Fantasy', 'Sci-Fi']",Jaume Collet-Serra,"['Rory Haines', 'Sohrab Noshirvani', 'Sarah Sh...",Adam Sztykiel,-2022
17,Bullet Train,no-rating,0,"['Action', 'Thriller']",David Leitch,"['Zak Olkewicz', 'Karen Fukuhara', 'Brad Pitt'...",KÃ´tarÃ´ Isaka,-2022
28,Prey,no-rating,0,"['Action', 'Drama', 'Horror']",Dan Trachtenberg,"['Amber Midthunder', 'Dane DiLiegro', 'Harlan ...",Patrick Aison,(I) (2022)
38,The Gray Man,no-rating,0,"['Action', 'Thriller']",Anthony Russo,"['Mark Greaney', 'Joe Russo', 'Christopher Mar...",Joe Russo,-2022
59,Avatar: The Way of Water,no-rating,0,"['Action', 'Adventure', 'Sci-Fi']",James Cameron,"['Josh Friedman', 'Michelle Yeoh', 'Zoe Saldan...",James Cameron,-2022
...,...,...,...,...,...,...,...,...
24242,Scheme Queens,no-rating,0,['Crime'],Cas Sigers-Beedles,"[""Brii Renee'"", 'Jason Louder', 'Sean Baker', ...",Cas Sigers-Beedles,-2022
24311,Penthouse,no-rating,0,"['Crime', 'Mystery', 'Thriller']",Abbas Alibhai Burmawalla,"['Girish Dhamija', 'Mouni Roy', 'Tisca Chopra'...",Mastan Alibhai Burmawalla,(I) (2022)
24355,Now I See,no-rating,0,"['Crime', 'Drama']",Carissa Stutzman,"['Annalise Basso', 'Steven Ogg', 'Deborah Tuck...",Carissa Stutzman,-2023
24377,Flycatcher,no-rating,0,"['Crime', 'Drama', 'Thriller']",Phil Volken,"['Phil Volken', 'Phil Volken', '2023 (United S...",Phil Volken,-2023
24379,Breakwater,no-rating,0,"['Crime', 'Drama', 'Thriller']",James Rowe,"['Mena Suvari', 'Dermot Mulroney', 'Celia Rose...",James Rowe,(I) (2022)

In [27]:
data = data[~((data['User Rating'] == '0') & (data['Rating'] == 'no-rating'))] 
# ~negates the condition to keep only the rows that don't match

In [28]:
data.columns= ['Movie Title', 'Rating','User Rating','Genre','Director','Top Casts','Writer','Year']

In [29]:
data.head()

,Movie Title,Rating,User Rating,Genre,Director,Top Casts,Writer,Year
0,Top Gun: Maverick,8.6,187K,"['Action', 'Drama']",Joseph Kosinski,"['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...",Jim Cash,-2022
1,Jurassic World Dominion,6,56K,"['Action', 'Adventure', 'Sci-Fi']",Colin Trevorrow,"['Colin Trevorrow', 'Derek Connolly', 'Chris P...",Emily Carmichael,-2022
2,Top Gun,6.9,380K,"['Action', 'Drama']",Tony Scott,"['Jack Epps Jr.', 'Ehud Yonay', 'Tom Cruise', ...",Jim Cash,-1986
3,Lightyear,5.2,32K,"['Animation', 'Action', 'Adventure']",Angus MacLane,"['Jason Headley', 'Matthew Aldrich', 'Chris Ev...",Angus MacLane,-2022
4,Spiderhead,5.4,23K,"['Action', 'Crime', 'Drama']",Joseph Kosinski,"['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...",George Saunders,-2022

In [30]:
data['Genre'].value_counts()

['Action', 'Crime', 'Drama']         824
['Drama']                            822
['Comedy', 'Drama', 'Romance']       595
['Crime', 'Drama', 'Thriller']       568
['Crime', 'Drama']                   506
                                    ...
['Adventure', 'Action', 'Drama']       1
['Comedy', 'Musical', 'Drama']         1
['Horror', 'Music', 'Sci-Fi']          1
['Animation', 'Fantasy', 'Music']      1
['Crime', 'Romance', 'Western']        1
Name: Genre, Length: 725, dtype: int64

In [31]:
data['Director'].value_counts()

Woody Allen                    46
Clint Eastwood                 38
Alfred Hitchcock               36
John Ford                      32
Henry Hathaway                 31
                               ..
Antoneta Alamat Kusijanovic     1
Machete Bang Bang               1
Yvan Attal                      1
Filippo Meneghetti              1
Bill Posley                     1
Name: Director, Length: 10638, dtype: int64

In [32]:
data['Top Casts'].value_counts()

['J.K. Rowling', 'Daniel Radcliffe', 'Emma Watson', 'Rupert Grint', 'David Yates']                 4
['Lilly Wachowski', 'Lana Wachowski', 'Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss']    3
['Sylvester Stallone', 'Talia Shire', 'Burt Young', 'Sylvester Stallone', 'Sylvester Stallone']    3
['Henning Bahs', 'Ove SprogÃ¸e', 'Morten Grunwald', 'Poul Bundgaard', 'Erik Balling']               3
['Mammootty', 'Mukesh', 'Jagathi Sreekumar', 'K. Madhu', 'S.N. Swamy']                             3
                                                                                                  ..
['Lukas Heller', 'Bette Davis', 'Joan Crawford', 'Victor Buono', 'Robert Aldrich']                 1
['David Lynch', 'Nicolas Cage', 'Laura Dern', 'Willem Dafoe', 'David Lynch']                       1
['Vanessa Kirby', 'Shia LaBeouf', 'Ellen Burstyn', 'KornÃ©l MundruczÃ³', 'Kata WÃ©ber']               1
['Alexandre Bustillo', 'Julien Maury', 'Rachel Parker', 'Camille Rowe', 'James Jagger']            1
['Abe Burrows', 'Damon Runyon', 'Marlon Brando', 'Jean Simmons', 'Frank Sinatra']                  1
Name: Top Casts, Length: 22162, dtype: int64

In [33]:
data['Year'].value_counts()

-2021          1027
-2019           897
-2018           791
-2017           763
-2020           761
               ...
(I) (1985)        1
(I) (1981)        1
(II) (1996)       1
(I) (1932)        1
(II) (1951)       1
Name: Year, Length: 235, dtype: int64

In [34]:
data['Rating'] = data['Rating'].astype(float)

C:\Users\User\AppData\Local\Temp\ipykernel_18472\2717106438.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Rating'] = data['Rating'].astype(float)

In [35]:
pd.options.mode.chained_assignment = None

In [36]:
data.dtypes

Movie Title     object
Rating         float64
User Rating     object
Genre           object
Director        object
Top Casts       object
Writer          object
Year            object
dtype: object

In [37]:
# data['Year'] = data['Year'].to_string()

In [38]:
#data['Year'] = data['Year'].str.replace('-', '', regex=True)

In [39]:
#data['Year'] = data['Year'].str.replace('(', '', regex=True)

In [40]:
#data['Year'] = data['Year'].str.replace(')', '', regex=True)

In [41]:
#data['Year'] = data['Year'].str.replace('I', '', regex=True)

# These modification would be done by using the Spreadsheet application i.e. MS Excel

# And further Data Cleaning will be done by using MS Excel only.

In [42]:
data.to_excel('Movie Dataset.xlsx', sheet_name='Records', index= False)